export const AUTH_INPUT_CHANGE = 'AUTH_INPUT_CHANGE';
export const AUTH_SUBMITTING = 'AUTH_SUBMITTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const FETCHING_ARTICLES = 'FETCHING_ARTICLE';
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES_FETCH_SUCCESS';
export const ARTICLES_FETCH_FAILED = 'ARTICLES_FETCH_FAILED';
